// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package alpha

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlphaServiceClient is the client API for AlphaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlphaServiceClient interface {
	SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type alphaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlphaServiceClient(cc grpc.ClientConnInterface) AlphaServiceClient {
	return &alphaServiceClient{cc}
}

func (c *alphaServiceClient) SayHello(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/AlphaService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlphaServiceServer is the server API for AlphaService service.
// All implementations must embed UnimplementedAlphaServiceServer
// for forward compatibility
type AlphaServiceServer interface {
	SayHello(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedAlphaServiceServer()
}

// UnimplementedAlphaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAlphaServiceServer struct {
}

func (UnimplementedAlphaServiceServer) SayHello(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedAlphaServiceServer) mustEmbedUnimplementedAlphaServiceServer() {}

// UnsafeAlphaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlphaServiceServer will
// result in compilation errors.
type UnsafeAlphaServiceServer interface {
	mustEmbedUnimplementedAlphaServiceServer()
}

func RegisterAlphaServiceServer(s grpc.ServiceRegistrar, srv AlphaServiceServer) {
	s.RegisterService(&AlphaService_ServiceDesc, srv)
}

func _AlphaService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlphaServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AlphaService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlphaServiceServer).SayHello(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// AlphaService_ServiceDesc is the grpc.ServiceDesc for AlphaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlphaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AlphaService",
	HandlerType: (*AlphaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _AlphaService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/serviceAlpha.proto",
}
